sudo: required

# Enable C++ support
language: cpp
cache: apt

# Compiler selection
compiler:
  - g++

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - libopencv-dev
      - libboost1.55-all-dev

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./src/main --help