sudo: false

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang++
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - clang-3.7
      - g++-5

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
